CREATE TABLE IF NOT EXISTS PUBLIC.USER(
    ID SERIAL,
    EMAIL VARCHAR(30) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(200) NOT NULL,
    BIRTHDAY VARCHAR(100)
);

ALTER TABLE PUBLIC.USER ADD CONSTRAINT PK_USER PRIMARY KEY (ID);
ALTER TABLE PUBLIC.USER ADD CONSTRAINT UK_USER_EMAIL UNIQUE (EMAIL);
 
CREATE TABLE IF NOT EXISTS PUBLIC.PROFILE (
    ID SERIAL,
    USER_ID VARCHAR(30) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    MAIN BOOLEAN NOT NULL DEFAULT 'FALSE'
);
ALTER TABLE PUBLIC.PROFILE ADD CONSTRAINT PK_PROFILE PRIMARY KEY (ID);


CREATE TABLE IF NOT EXISTS PUBLIC.MOVIES (
    ID SERIAL,
    PROFILE_ID VARCHAR(30) NOT NULL,
    MOVIE_ID VARCHAR(100) NOT NULL,
    WATCHED NOT NULL DEFAULT 'FALSE'
);
ALTER TABLE PUBLIC.PROFILE ADD CONSTRAINT PK_USER PRIMARY KEY (ID);
