CREATE TABLE IF NOT EXISTS PUBLIC.USER(
    ID SERIAL,
    EMAIL VARCHAR(30),
    NAME VARCHAR(100),
    PASSWORD VARCHAR(200),
	BIRTHDAY VARCHAR(100)
);


ALTER TABLE PUBLIC.USER ADD CONSTRAINT UK_USER_EMAIL UNIQUE (EMAIL);